destroy level0

diff --git a/.github/workflows/landingzones-tf.yml b/.github/workflows/landingzones-tf.yml
--- a/.github/workflows/landingzones-tf.yml
+++ b/.github/workflows/landingzones-tf.yml
@@ -50,17 +50,17 @@ jobs:
 
           echo "local user: $(whoami)"
 
-      # - name: launchpad
-      #   run: |
-      #     /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/caf_launchpad -a apply \
-      #       -var-folder ${GITHUB_WORKSPACE}/caf_launchpad/scenario/100 \
-      #       -level level0 \
-      #       -launchpad \
-      #       -parallelism=30 \
-      #       --environment ${{ github.run_id }} \
-      #       '-var random_length=${{ matrix.random_length }}' \
-      #       '-var prefix=g${{ github.run_id }}' \
-      #       '-var tags={testing_job_id="${{ github.run_id }}"}'
+      - name: launchpad
+        run: |
+          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/caf_launchpad -a destroy \
+            -var-folder ${GITHUB_WORKSPACE}/caf_launchpad/scenario/100 \
+            -level level0 \
+            -launchpad \
+            -parallelism=30 \
+            --environment ${{ github.run_id }} \
+            '-var random_length=${{ matrix.random_length }}' \
+            '-var prefix=g${{ github.run_id }}' \
+            '-var tags={testing_job_id="${{ github.run_id }}"}'
 
       # - name: foundations
       #   run: |
@@ -214,62 +214,62 @@ jobs:
   #           --environment ${{ github.run_id }} \
   #           -refresh=false
 
-  foundations_destroy:
-    name: foundations_destroy
-    runs-on: ubuntu-latest
-    if: always()
-    # needs: networking200
+  # foundations_destroy:
+  #   name: foundations_destroy
+  #   runs-on: ubuntu-latest
+  #   if: always()
+  #   # needs: networking200
 
-    strategy:
-      fail-fast: false
-      matrix:
-        random_length: ['5']
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       random_length: ['5']
 
-    container:
-      image: aztfmod/rover:0.15.5-2203.2311
-      options: --user 0
+  #   container:
+  #     image: aztfmod/rover:0.15.5-2203.2311
+  #     options: --user 0
 
-    steps:
-      - uses: actions/checkout@v2
+  #   steps:
+  #     - uses: actions/checkout@v2
 
-      - name: Login azure
-        run: |
-          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
-          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}
+  #     - name: Login azure
+  #       run: |
+  #         az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
+  #         az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}
 
-          echo "local user: $(whoami)"
+  #         echo "local user: $(whoami)"
 
-      - name: foundations
-        run: |
-          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/caf_solution -a destroy \
-            -var-folder ${GITHUB_WORKSPACE}/caf_solution/scenario/foundations/gitops \
-            -tfstate caf_foundations.tfstate \
-            -level level1 \
-            -parallelism=30 \
-            --environment ${{ github.run_id }} \
-            '-var tags={testing_job_id="${{ github.run_id }}"}'
+  #     - name: foundations
+  #       run: |
+  #         /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/caf_solution -a destroy \
+  #           -var-folder ${GITHUB_WORKSPACE}/caf_solution/scenario/foundations/gitops \
+  #           -tfstate caf_foundations.tfstate \
+  #           -level level1 \
+  #           -parallelism=30 \
+  #           --environment ${{ github.run_id }} \
+  #           '-var tags={testing_job_id="${{ github.run_id }}"}'
 
-      - name: Remove launchpad
-        run: |
-          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/caf_launchpad -a destroy \
-            -var-folder ${GITHUB_WORKSPACE}/caf_launchpad/scenario/100 \
-            -level level0 \
-            -launchpad \
-            -parallelism=30 \
-            --environment ${{ github.run_id }} \
-            '-var random_length=${{ matrix.random_length }}' \
-            '-var prefix=g${{ github.run_id }}' \
-            '-var tags={testing_job_id="${{ github.run_id }}"}'
+  #     - name: Remove launchpad
+  #       run: |
+  #         /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/caf_launchpad -a destroy \
+  #           -var-folder ${GITHUB_WORKSPACE}/caf_launchpad/scenario/100 \
+  #           -level level0 \
+  #           -launchpad \
+  #           -parallelism=30 \
+  #           --environment ${{ github.run_id }} \
+  #           '-var random_length=${{ matrix.random_length }}' \
+  #           '-var prefix=g${{ github.run_id }}' \
+  #           '-var tags={testing_job_id="${{ github.run_id }}"}'
 
 
-      - name: Complete purge
-        if: ${{ always() }}
-        run: |
-          for i in `az monitor diagnostic-settings subscription list -o tsv --query "value[?contains(name, '${{ github.run_id }}' )].name"`; do echo "purging subscription diagnostic-settings: $i" && $(az monitor diagnostic-settings subscription delete --name $i --yes); done
-          for i in `az monitor log-profiles list -o tsv --query '[].name'`; do az monitor log-profiles delete --name $i; done
-          for i in `az ad group list --query "[?contains(displayName, '${{ github.run_id }}')].objectId" -o tsv`; do echo "purging Azure AD group: $i" && $(az ad group delete --verbose --group $i || true); done
-          for i in `az ad app list --query "[?contains(displayName, '${{ github.run_id }}')].appId" -o tsv`; do echo "purging Azure AD app: $i" && $(az ad app delete --verbose --id $i || true); done
-          for i in `az keyvault list-deleted --query "[?tags.environment=='${{ github.run_id }}'].name" -o tsv`; do az keyvault purge --name $i; done
-          for i in `az group list --query "[?tags.environment=='${{ github.run_id }}'].name" -o tsv`; do echo "purging resource group: $i" && $(az group delete -n $i -y --no-wait || true); done
-          for i in `az role assignment list --query "[?contains(roleDefinitionName, '${{ github.run_id }}')].roleDefinitionName" -o tsv`; do echo "purging role assignment: $i" && $(az role assignment delete --role $i || true); done
-          for i in `az role definition list --query "[?contains(roleName, '${{ github.run_id }}')].roleName" -o tsv`; do echo "purging custom role definition: $i" && $(az role definition delete --name $i || true); done
+  #     - name: Complete purge
+  #       if: ${{ always() }}
+  #       run: |
+  #         for i in `az monitor diagnostic-settings subscription list -o tsv --query "value[?contains(name, '${{ github.run_id }}' )].name"`; do echo "purging subscription diagnostic-settings: $i" && $(az monitor diagnostic-settings subscription delete --name $i --yes); done
+  #         for i in `az monitor log-profiles list -o tsv --query '[].name'`; do az monitor log-profiles delete --name $i; done
+  #         for i in `az ad group list --query "[?contains(displayName, '${{ github.run_id }}')].objectId" -o tsv`; do echo "purging Azure AD group: $i" && $(az ad group delete --verbose --group $i || true); done
+  #         for i in `az ad app list --query "[?contains(displayName, '${{ github.run_id }}')].appId" -o tsv`; do echo "purging Azure AD app: $i" && $(az ad app delete --verbose --id $i || true); done
+  #         for i in `az keyvault list-deleted --query "[?tags.environment=='${{ github.run_id }}'].name" -o tsv`; do az keyvault purge --name $i; done
+  #         for i in `az group list --query "[?tags.environment=='${{ github.run_id }}'].name" -o tsv`; do echo "purging resource group: $i" && $(az group delete -n $i -y --no-wait || true); done
+  #         for i in `az role assignment list --query "[?contains(roleDefinitionName, '${{ github.run_id }}')].roleDefinitionName" -o tsv`; do echo "purging role assignment: $i" && $(az role assignment delete --role $i || true); done
+  #         for i in `az role definition list --query "[?contains(roleName, '${{ github.run_id }}')].roleName" -o tsv`; do echo "purging custom role definition: $i" && $(az role definition delete --name $i || true); done
